module ActsAsCensored

  def self.included(base)
    base.extend(ClassMethods)
  end
  
  module ClassMethods
    def acts_as_censored(*args, options={})
      bleep_value = options[:with].nil? ? '&%$!@' : options[:with]
      args.each do |column|
        before_save do |record|
          record[column] = record[column].gsub!(sub!(%r{"(#{RESTRICTED_WORDS.join("|")})"},''),bleep_value)
        end
      end
    end
  end
  
  RESTRICTED_WORDS = [
    'anoint',
    'approach',
    'avuncular',
    '(.+)ass(.+)'
    'back-hoe',
    'bent',
    'buckle',
    'bud',
    'bulge',
    'burgle',
    'chum',
    'cleft',
    'clog',
    'cloister',
    'crampon',
    'cranny',
    'Croce',
    'dangle',
    'dip',
    'discharge',
    'dongle',
    'Do you like salt on your rim?',
    'Dukakis',
    'effluvia',
    'encroach',
    'extrude',
    'fattoush / fatoush',
    'flow',
    'fluid',
    'foist',
    '(.+)fuck(.+)',
    'gaping',
    'gleatinous',
    'gnaw',
    'gramps',
    'gravy',
    'gush',
    'handle',
    'heap',
    'hoist',
    'hot pocket',
    'implement',
    'inert',
    'issue',
    'jam',
    'jelly',
    'juice',
    'juice-box',
    'knob',
    'labile ',
    'lacrimal',
    'leakage',
    'load ',
    'loaf',
    'lube',
    'lump',
    'meal',
    'membrane',
    'moist',
    'notch',
    'nugget',
    'onus',
    'paginate',
    'papal',
    'pentile',
    'perturb',
    'pester',
    'pilaf',
    'pile',
    'plug',
    'plump',
    'plunder',
    'poke',
    'pony',
    'pouch ',
    'proctor',
    'prong',
    'pucker',
    'puny',
    'putty',
    'ramp',
    'receptacle',
    'rictus',
    'rub',
    '(.+)shit(.+)'
    'shooting blanks in the red zone',
    'slab',
    'slat',
    'sloppy beef and wet',
    'snack',
    'snicker ',
    'snorkel',
    'snout',
    'soft spot in the crust',
    'Sophocles',
    'spackle',
    'spake',
    'spectate',
    'spew',
    'spill',
    'spray mount',
    'spread',
    'spunk',
    'squirt',
    'stew',
    'stew',
    'stuff',
    'stump',
    'subpoena',
    'supine',
    'tang',
    'thick',
    'tongue and groove',
    'tool',
    'trickle',
    'tutelage',
    'usage',
    'vascillate',
    'wet-exit',
    'whack',
    'wipe'
  ]
end

class ActiveRecord::Base
  include ActsAsCensored
end